-- ------------------------------------------------- PROCEDURES -----------------------------


  -- ACTUALIZA CLIENTE --
CREATE PROCEDURE `UPDATE_CLIENTE` (`PREV_NIT` VARCHAR(15),`NIT_CLIENTE` VARCHAR(15),`NC_IN` VARCHAR(45),
`AC_IN` VARCHAR(45),`DIR`VARCHAR(128),`TC_IN` VARCHAR(15),`TEC_IN` VARCHAR(15), `DIAS` INT, `LIMITE` FLOAT, `DISPONIBLE` FLOAT) 
  UPDATE CLIENTE SET ESTADO_TUPLA = TRUE,
  ID_CLIENTE = NIT_CLIENTE,
  NOMBRE_CLIENTE = NC_IN,
  APELLIDO_CLIENTE = AC_IN,
  TELEFONO_CLIENTE = TEC_IN,
  DIRECCION_CLIENTE = DIR,
  ID_TIPO_CLIENTE = (SELECT ID_TIPO_CLIENTE FROM TIPO_CLIENTE WHERE TIPO = TC_IN LIMIT 1),
  LIMITE_CREDITO = LIMITE,
  CREDITO_DISPONIBLE = DISPONIBLE,
  DIAS_CREDITO = DIAS
  WHERE ID_CLIENTE = PREV_NIT;
  



 -- SP ELIMINA CLIENTE --
CREATE PROCEDURE `ELIMINAR_CLIENTE` (`NIT_CLIENTE` VARCHAR(15)) 
  UPDATE CLIENTE SET ESTADO_TUPLA = FALSE WHERE ID_CLIENTE = NIT_CLIENTE;


 -- SP PARA INGRESO CLIENTE --
CREATE PROCEDURE `INGRESO_CLIENTE` (`ID_CLIENTE` VARCHAR(15), `NOMBRE_CLIENTE` VARCHAR(45),`APELLIDO_CLIENTE` VARCHAR(45),
`DIRECCION` VARCHAR(128),`TELEFONO_CLIENTE` VARCHAR(15),`LIMITE` FLOAT,`DIAS` INT,`TIPO_C` VARCHAR(45)) 
 INSERT INTO CLIENTE VALUES (ID_CLIENTE,(SELECT ID_TIPO_CLIENTE FROM TIPO_CLIENTE WHERE TIPO = TIPO_C LIMIT 1),
 NOMBRE_CLIENTE,APELLIDO_CLIENTE,DIRECCION,TELEFONO_CLIENTE,LIMITE,LIMITE,DIAS,NOW(),TRUE);



-- SP ELIMINA PROVEEDOR --
CREATE PROCEDURE `ELIMINAR_PROVEEDOR` (`ID_PD` VARCHAR(45)) 
  UPDATE PROVEEDOR SET ESTADO_TUPLA = FALSE WHERE ID_PROVEEDOR = ID_PD;
  


 -- SP PARA INGRESO PROVEEDOR --
CREATE PROCEDURE `INGRESO_PROVEEDOR` (`ID_PROVEEDOR` VARCHAR(45) ,`NOMBRE_PROVEEDOR` VARCHAR(45),
`EMAIL_PROVEEDOR` VARCHAR(45),`DIR_PROVEEDOR` VARCHAR(45),`TELEFONO_PROVEEDOR` VARCHAR(45)) 
 INSERT INTO PROVEEDOR VALUES (ID_PROVEEDOR,NOMBRE_PROVEEDOR,EMAIL_PROVEEDOR,DIR_PROVEEDOR,TELEFONO_PROVEEDOR,NOW(),TRUE);
 



  -- SP ACTUAIZA PROVEEDOR --
CREATE PROCEDURE `UPDATE_PROVEEDOR` (`ID_PD` VARCHAR(45),`ID_PROVEEDORN` VARCHAR(45) ,
`NM_PROVEEDOR` VARCHAR(45),`EM_PROVEEDOR` VARCHAR(45),`DIR_PROVEEDOR` VARCHAR(45),`TEL_PROVEEDOR` VARCHAR(45)) 
  UPDATE PROVEEDOR SET ESTADO_TUPLA = TRUE,
  ID_PROVEEDOR = ID_PROVEEDORN,
  NOMBRE_PROVEEDOR = NM_PROVEEDOR,
  EMAIL_PROVEEDOR = EM_PROVEEDOR,
  DIRECCION_PROVEEDOR = DIR_PROVEEDOR,
  TELEFONO_PROVEEDOR = TEL_PROVEEDOR
  WHERE ID_PROVEEDOR = ID_PD;
  
  
CREATE PROCEDURE `UPDATE_SUCURSAL` (`SUCURSAL` INT,`NOMBRE` VARCHAR(45),`DIRECCION` VARCHAR(45),`TELEFONO` VARCHAR(45),`TIPO` VARCHAR(45)) 
  UPDATE SUCURSAL SET 
  NOMBRE_SUCURSAL = NOMBRE,
  DIRECCION_SUCURSAL = DIRECCION,
  TELEFONO_SUCURSAL = TELEFONO,
  ID_TIPO = (SELECT ID_TIPO FROM TIPO_SUCURSAL WHERE TIPO_SUCURSAL = TIPO LIMIT 1)
  WHERE ID_SUCURSAL = SUCURSAL;
  

 
 -- ------ CONTROL DE MERCADERIA --------------------------------------------------------------------

CREATE PROCEDURE `INGRESA_MERCADERIA` (`CODIGO` VARCHAR(45),`SUCURSAL` VARCHAR(45),`PROVEEDOR` VARCHAR(45),`DESCR` VARCHAR(45),
`PRECIO_C` FLOAT,`TOTAL_UNIDADES` FLOAT,`ACTIVO` BOOLEAN) 
	INSERT INTO MERCADERIA VALUES (CODIGO,(SELECT ID_SUCURSAL FROM SUCURSAL WHERE NOMBRE_SUCURSAL = SUCURSAL LIMIT 1),1,
    (SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE_PROVEEDOR = PROVEEDOR AND ESTADO_TUPLA = TRUE LIMIT 1),
     DESCR,PRECIO_C,TOTAL_UNIDADES,ACTIVO,NOW(),TRUE);
     
     

CREATE PROCEDURE `INGRESA_ESPECIAS` (`CODIGO` VARCHAR(45),`SUCURSAL` VARCHAR(45),`PROVEEDOR` VARCHAR(45),`DESCR` VARCHAR(45),
`PRECIO_C` FLOAT,`TOTAL_UNIDADES` FLOAT,`ACTIVO` BOOLEAN) 
	INSERT INTO MERCADERIA VALUES (CODIGO,(SELECT ID_SUCURSAL FROM SUCURSAL WHERE NOMBRE_SUCURSAL = SUCURSAL LIMIT 1),2,
    (SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE_PROVEEDOR = PROVEEDOR AND ESTADO_TUPLA = TRUE LIMIT 1),
     DESCR,PRECIO_C,TOTAL_UNIDADES,ACTIVO,NOW(),TRUE);
     
   

CREATE PROCEDURE `INGRESA_STOCK` (`ID_STOCK` VARCHAR(45),`ID_MERCADERIA` VARCHAR(20), `DESCR` VARCHAR(120),
   `CANTIDAD_PP` DOUBLE, `TOTAL_P` DOUBLE, `CANT_M` DOUBLE, `P_1` DOUBLE, `P_2` DOUBLE,
   `P_3` DOUBLE, `P_4` DOUBLE, `P_5` DOUBLE, `P_6` DOUBLE,`UT_1` DOUBLE, `UT_2` DOUBLE, `UT_3` DOUBLE,
   `UT_4` DOUBLE, `UT_5` DOUBLE, `SUCURSAL` VARCHAR(45))
    INSERT INTO MERCADERIA_PRESENTACIONES VALUES (ID_STOCK, (SELECT ID_SUCURSAL FROM SUCURSAL WHERE NOMBRE_SUCURSAL = SUCURSAL LIMIT 1),
    ID_MERCADERIA,DESCR,CANTIDAD_PP,TOTAL_P,CANT_M,
    P_1,P_2,P_3,P_4,P_5,P_6,UT_1,UT_2,UT_3,UT_4,UT_5,NOW(),TRUE);

  
    

CREATE PROCEDURE `UPDATE_MERCADERIA_X` (`CODIGO` VARCHAR(45),`PRECIO_C` FLOAT, `TOTAL_U` FLOAT,`SUCURSAL` VARCHAR(45))
 UPDATE MERCADERIA SET 
  PRECIO_COMPRA = PRECIO_C,
  TOTAL_UNIDADES = TOTAL_U
  WHERE ID_MERCADERIA = CODIGO AND ID_SUCURSAL = (SELECT ID_SUCURSAL FROM SUCURSAL WHERE NOMBRE_SUCURSAL = SUCURSAL LIMIT 1);

  
CREATE PROCEDURE `UPDATE_STOCK` (`ID_ST` VARCHAR(45),`ID_MERC` VARCHAR(45), `DESCR` VARCHAR(120),
   `CANTIDAD_PP` DOUBLE, `TOTAL_P` DOUBLE, `CANT_M` DOUBLE, `P_1` DOUBLE, `P_2` DOUBLE,
   `P_3` DOUBLE, `P_4` DOUBLE, `P_5` DOUBLE, `P_6` DOUBLE, `UT_1` DOUBLE, `UT_2` DOUBLE, `UT_3` DOUBLE,
   `UT_4` DOUBLE, `UT_5` DOUBLE, `SUCURSAL` VARCHAR(45))
    UPDATE MERCADERIA_PRESENTACIONES SET
    DESCRIPCION = DESCR,
    CANTIDAD_POR_PRESENTACION = CANTIDAD_PP,
    TOTAL_PRESENTACIONES = TOTAL_P,
    CANTIDAD_MINIMA = CANT_M,
    PRECIO_1 = P_1,
    PRECIO_2 = P_2,
    PRECIO_3 = P_3,
    PRECIO_4 = P_4,
    PRECIO_5 = P_5,
    PRECIO_6 = P_6,
    UTILIDAD_1 = UT_1,
    UTILIDAD_2 = UT_2,
    UTILIDAD_3 = UT_3,
    UTILIDAD_4 = UT_4,
    UTILIDAD_5 = UT_5
    WHERE ID_STOCK = ID_ST AND ID_MERCADERIA = ID_MERC AND ID_SUCURSAL = (SELECT ID_SUCURSAL FROM SUCURSAL WHERE NOMBRE_SUCURSAL = SUCURSAL LIMIT 1);
    
    
    
    CREATE PROCEDURE `NUEVA_COMPRA` (`ID_C` INT,`USER_S` VARCHAR(25),`SUCURSAL` VARCHAR(45), `PROVEEDOR` VARCHAR(45))
     INSERT INTO COMPRA VALUES (ID_C,(SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE_PROVEEDOR = PROVEEDOR LIMIT 1),
     (SELECT ID_SUCURSAL FROM SUCURSAL WHERE NOMBRE_SUCURSAL = SUCURSAL LIMIT 1),
     USER_S,NOW(),0,0,0,0,TRUE);
     

     
	CREATE PROCEDURE `DETALLE_COMPRA` (`ID_COM` INT,`ID_MERC` VARCHAR(45),`CANTIDAD` FLOAT,`PRECIO` FLOAT,`GASTOS` FLOAT, `SUBTOTAL` FLOAT)
     INSERT INTO CONTROL_COMPRA VALUES (NULL,ID_COM,ID_MERC,CANTIDAD,PRECIO,GASTOS,SUBTOTAL);
     

    CREATE PROCEDURE `GET_COMPRA` (`ID_COM` INT)
     SELECT  C.SUBTOTAL FROM CONTROL_COMPRA C WHERE ID_COMPRA = ID_COM;
	
    CREATE PROCEDURE `CIERRA_COMPRA` (`ID_C` INT,`SUBTOTAL` FLOAT, `DESCUENTOS` FLOAT, `TOTAL` FLOAT)
     UPDATE COMPRA SET 
     SUBTOTAL_COMPRA = SUBTOTAL,
     DESCUENTO  = DESCUENTOS,
     TOTAL_FINAL = TOTAL
     WHERE ID_COMPRA = ID_C;
     
     
	CREATE PROCEDURE `INGRESA_USUARIO` (`ID_USER` VARCHAR(25),`ID_ROL` VARCHAR(45), `PASS` VARCHAR(25) ,
    `NOMBRE` VARCHAR(45),`EMAIL` VARCHAR(90),`ESTADO` BOOL, `IMAGE` BLOB)
     INSERT INTO USUARIO VALUES (ID_USER, ID_ROL, PASS,NOMBRE,EMAIL,ESTADO,IMAGE,NOW(),TRUE);
     
  
	
   CREATE PROCEDURE `ACTUALIZA_USUARIO` (`USUARIO` VARCHAR(25), `NOMBRE` VARCHAR(45),
   `MAIL` VARCHAR(90),`ROL` VARCHAR(45), `ESTADO` BOOL, `IMAGE` VARCHAR(150) )
   UPDATE USUARIO SET NOMBRE_USUARIO = NOMBRE,
   EMAIL = MAIL,
   ID_ROL = ROL,
   IMAGEUSER = IMAGE,
   ESTADO_USUARIO = ESTADO
   WHERE ID_USUARIO = USUARIO;
      
   
   CREATE PROCEDURE `UPDATE_BITACORA` (`ID_SUC` INT, `ID_USU` VARCHAR(25),`OPE` VARCHAR(150),
   `D_OPERACION` VARCHAR (45),`IP` VARCHAR(45))
    INSERT INTO BITACORA VALUES (NULL,ID_SUC, ID_USU,OPE,D_OPERACION,NOW(),IP);
    
    
  CREATE PROCEDURE `UPDATE_CONFIG` (`ID_CONFIG` INT, `IMAGEN` BOOL, `NOTIFY` BOOL,
  `ACTUA` BOOL, `LASTLOG` BOOL, `FACTURA` BOOL, `CAJAD` BOOL, `IMPRESION` BOOL)
   UPDATE CONFIGURACION_SISTEMA S SET MOSTRAR_IMAGEN = IMAGEN,
   S.MOSTRAR_NOTIFICACION = NOTIFY,
   ACTUALIZACION = ACTUA,
   ULTIMO_INICIO = LASTLOG,
   FACTURA_DEFECTO = FACTURA,
   CAJA = CAJAD,
   IMPRESION_DEFECTO = IMPRESION
   WHERE IDCONFIGURACION = ID_CONFIG;
   


   
   CREATE PROCEDURE `INSERT_ALTER_CODES` (`ID_MERC` VARCHAR(45),`ID_CODE` VARCHAR(65))
   INSERT INTO SUBCODIGOS_MERCADERIA VALUES (ID_MERC, ID_CODE,TRUE);
   







                                   -- PROCEDIMIENTOS PARA TRASLADOS DE MERCADERIA ----

CREATE PROCEDURE `UPDATE_MERCADERIA_TRASLADO` (`CODIGO` VARCHAR(45),`PRECIO_C` FLOAT, `TOTAL_U` FLOAT, `SUCURSAL` VARCHAR(45))
 UPDATE MERCADERIA SET 
  PRECIO_COMPRA = PRECIO_C,
  TOTAL_UNIDADES = TOTAL_U
  WHERE ID_MERCADERIA = CODIGO AND ID_SUCURSAL = (SELECT ID_SUCURSAL FROM SUCURSAL WHERE NOMBRE_SUCURSAL  = SUCURSAL LIMIT 1);  
   
CREATE PROCEDURE `UPDATE_STOCK_TRASLADO` (`ID_ST` VARCHAR(45),`ID_MERC` VARCHAR(45), `DESCR` VARCHAR(120),
   `CANTIDAD_PP` DOUBLE, `TOTAL_P` DOUBLE, `CANT_M` DOUBLE, `P_1` DOUBLE, `P_2` DOUBLE,
   `P_3` DOUBLE, `P_4` DOUBLE,`P_5` DOUBLE, `P_6` DOUBLE, `UT_1` DOUBLE, `UT_2` DOUBLE, `UT_3` DOUBLE,
   `UT_4` DOUBLE, `UT_5` DOUBLE,`SUCURSAL` VARCHAR(45))
    UPDATE MERCADERIA_PRESENTACIONES SET
    DESCRIPCION = DESCR,
    CANTIDAD_POR_PRESENTACION = CANTIDAD_PP,
    TOTAL_PRESENTACIONES = TOTAL_P,
    CANTIDAD_MINIMA = CANT_M,
    PRECIO_1 = P_1,
    PRECIO_2 = P_2,
    PRECIO_3 = P_3,
    PRECIO_4 = P_4,
    PRECIO_5 = P_5,
    UTILIDAD_1 = UT_1,
    UTILIDAD_2 = UT_2,
    UTILIDAD_3 = UT_3,
    UTILIDAD_4 = UT_4,
    UTILIDAD_5 = UT_5
    WHERE ID_STOCK = ID_ST AND ID_MERCADERIA = ID_MERC AND ID_SUCURSAL = (SELECT ID_SUCURSAL FROM SUCURSAL WHERE NOMBRE_SUCURSAL  = SUCURSAL LIMIT 1);

 --  DROP PROCEDURE UPDATE_STOCK_TRASLADO;
 -- TRASLADO DE ABARROTES INGRESO COMPLETO--
   
CREATE PROCEDURE `INGRESA_MERCADERIA_SUCURSAL` (`CODIGO` VARCHAR(45),`NSUCURSAL` VARCHAR(45),`PROVEEDOR` VARCHAR(45),
`DESCR` VARCHAR(45),`PRECIO_C` FLOAT,`TOTAL_UNIDADES` FLOAT,`ACTIVO` BOOLEAN) 
	INSERT INTO MERCADERIA VALUES (CODIGO,(SELECT ID_SUCURSAL FROM SUCURSAL WHERE NOMBRE_SUCURSAL = NSUCURSAL AND ESTADO_TUPLA = TRUE LIMIT 1),
    1, (SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE_PROVEEDOR = PROVEEDOR AND ESTADO_TUPLA = TRUE LIMIT 1),
     DESCR,PRECIO_C,TOTAL_UNIDADES,ACTIVO,NOW(),TRUE);
     
 -- PRIMER INGRESO DE TRASLADO APLICA A AMBOS TIPOS DE MERCADERIA --    
CREATE PROCEDURE `INGRESA_STOCK_TRASLADO` (`ID_STOCK` VARCHAR(45),`ID_MERCADERIA` VARCHAR(45),`NSUCURSAL` VARCHAR(45),
 `DESCR` VARCHAR(120), `CANTIDAD_PP` DOUBLE, `TOTAL_P` DOUBLE, `CANT_M` DOUBLE, `P_1` DOUBLE, `P_2` DOUBLE,
   `P_3` DOUBLE, `P_4` DOUBLE,`P_5` DOUBLE ,`P_6` DOUBLE, `UT_1` DOUBLE, `UT_2` DOUBLE, `UT_3` DOUBLE,
   `UT_4` DOUBLE, `UT_5` DOUBLE)
    INSERT INTO MERCADERIA_PRESENTACIONES VALUES (ID_STOCK, (SELECT ID_SUCURSAL FROM SUCURSAL WHERE NOMBRE_SUCURSAL = NSUCURSAL AND ESTADO_TUPLA = TRUE LIMIT 1),ID_MERCADERIA,
    DESCR,CANTIDAD_PP,TOTAL_P,CANT_M,P_1,P_2,P_3,P_4,P_5,P_6,UT_1,UT_2,UT_3,UT_4,UT_5,NOW(),TRUE);
    
    CREATE PROCEDURE `INGRESA_STOCK_TRASLADO_ACTUALIZACION` (`ID_STOCK` VARCHAR(45),`ID_MERCADERIA` VARCHAR(45),`SUCURSAL` INT,
 `DESCR` VARCHAR(120), `CANTIDAD_PP` DOUBLE, `TOTAL_P` DOUBLE, `CANT_M` DOUBLE, `P_1` DOUBLE, `P_2` DOUBLE,
   `P_3` DOUBLE, `P_4` DOUBLE,`P_5` DOUBLE ,`P_6` DOUBLE, `UT_1` DOUBLE, `UT_2` DOUBLE, `UT_3` DOUBLE,
   `UT_4` DOUBLE, `UT_5` DOUBLE)
    INSERT INTO MERCADERIA_PRESENTACIONES VALUES (ID_STOCK, SUCURSAL,ID_MERCADERIA,
    DESCR,CANTIDAD_PP,TOTAL_P,CANT_M,P_1,P_2,P_3,P_4,P_5,P_6,UT_1,UT_2,UT_3,UT_4,UT_5,NOW(),TRUE);
    
 -- DROP PROCEDURE INGRESA_STOCK_TRASLADO;
     
 -- TRASLADO DE ABARROTES ACTUALIZACION DE ABARROTES Y ESPECIAS --
 
    -- UPDATE TRASLADO SP'S ANTERIORES 'REF'
    -- UPDATE STOCK TRASLADO SP'S ANTERIORES 'REF'
 
 -- TRASLADO DE ESPECIAS INGRESO COMPLETO --
 
 CREATE PROCEDURE `INGRESA_ESPECIAS_SUCURSAL` (`CODIGO` VARCHAR(45),`NSUCURSAL` VARCHAR(60),`PROVEEDOR` VARCHAR(45),`DESCR` VARCHAR(45),
`PRECIO_C` FLOAT,`TOTAL_UNIDADES` FLOAT,`ACTIVO` BOOLEAN) 
	INSERT INTO MERCADERIA VALUES (CODIGO,(SELECT ID_SUCURSAL FROM SUCURSAL WHERE NOMBRE_SUCURSAL = NSUCURSAL AND ESTADO_TUPLA = TRUE LIMIT 1),
    2,(SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE_PROVEEDOR = PROVEEDOR AND ESTADO_TUPLA = TRUE LIMIT 1),
     DESCR,PRECIO_C,TOTAL_UNIDADES,ACTIVO,NOW(),TRUE);


CREATE PROCEDURE `UPDATE_MERCADERIA_TRASLADOS` (`CODIGO` VARCHAR(45),`PRECIO_C` FLOAT, `TOTAL_U` FLOAT, `SUCURSAL` VARCHAR(45))
 UPDATE MERCADERIA SET 
  PRECIO_COMPRA = PRECIO_C,
  TOTAL_UNIDADES = TOTAL_UNIDADES +TOTAL_U
  WHERE ID_MERCADERIA = CODIGO AND ID_SUCURSAL = (SELECT ID_SUCURSAL FROM SUCURSAL WHERE NOMBRE_SUCURSAL  = SUCURSAL LIMIT 1);  



-- PROCEDIMIENTOS PARA EDICION DE MERCADERIA --


CREATE PROCEDURE `UPDATE_MERCADERIA_EDICION` (`CODIGO` VARCHAR(45),`CODIGO_N` VARCHAR(45),`PRECIO_C` FLOAT, 
`DESCR` VARCHAR(120),`PROVEEDOR` VARCHAR(45),`TOTAL_U` FLOAT, `SUCURSAL` VARCHAR(45))
 UPDATE MERCADERIA SET 
  ID_MERCADERIA = CODIGO_N,
  DESCRIPCION = DESCR,
  ID_PROVEEDOR = (SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE_PROVEEDOR = PROVEEDOR AND ESTADO_TUPLA = TRUE LIMIT 1),
  PRECIO_COMPRA = PRECIO_C,
  TOTAL_UNIDADES = TOTAL_U
  WHERE ID_MERCADERIA = CODIGO AND ID_SUCURSAL = (SELECT ID_SUCURSAL FROM SUCURSAL WHERE NOMBRE_SUCURSAL = SUCURSAL LIMIT 1);  
  

  
CREATE PROCEDURE `UPDATE_MERCADERIA_GENERAL` (`CODIGO` VARCHAR(45),`CODIGO_N` VARCHAR(45), 
`DESCR` VARCHAR(120),`PROVEEDOR` VARCHAR(45),`PRECIO` FLOAT)
 UPDATE MERCADERIA SET 
  ID_MERCADERIA = CODIGO_N,
  DESCRIPCION = DESCR,
  ID_PROVEEDOR = (SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE_PROVEEDOR = PROVEEDOR AND ESTADO_TUPLA = TRUE LIMIT 1),
  PRECIO_COMPRA = PRECIO
  WHERE ID_MERCADERIA = CODIGO;  
  
 
  
  CREATE PROCEDURE `UPDATE_MERCADERIA_COMPRAS` (`CODIGO` VARCHAR(45), 
`DESCR` VARCHAR(120),`PROVEEDOR` VARCHAR(45),`PRECIO` FLOAT)
 UPDATE MERCADERIA SET 
  DESCRIPCION = DESCR,
  ID_PROVEEDOR = (SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE_PROVEEDOR = PROVEEDOR AND ESTADO_TUPLA = TRUE LIMIT 1),
  PRECIO_COMPRA = PRECIO
  WHERE ID_MERCADERIA = CODIGO;  
  
   
   
   
   
   
-- PROCEDIMIENTSO PARA VENTAS --

CREATE PROCEDURE `NUEVA_FACTURA` (`CODIGO` VARCHAR(25),`VENDEDOR` VARCHAR(25),`VENCE` DATE,`SUCURSAL` INT,  `CLIENTE` VARCHAR(15), `SUBTOTAL` FLOAT,
 `DESCUENT` FLOAT, `TOTAL` FLOAT,`TIPO` VARCHAR(45), `DESCRI` VARCHAR(150))
  INSERT INTO FACTURA VALUES (CODIGO,
  (SELECT ID_USUARIO FROM USUARIO WHERE NOMBRE_USUARIO = VENDEDOR AND ESTADO_TUPLA = TRUE LIMIT 1),
  SUCURSAL,CLIENTE,NOW(),VENCE,SUBTOTAL,DESCUENT,TOTAL,TIPO,DESCRI,TRUE,1);
  
  
  CREATE PROCEDURE `ACTUALIZA_FACTURA` (`CODIGO` VARCHAR(25),`VENDEDOR` VARCHAR(25),`VENCE` DATE,`SUCURSAL` INT,  `CLIENTE` VARCHAR(15), `SUBTOTAL` FLOAT,
 `DESCUENT` FLOAT, `TOTAL` FLOAT,`TIPO` VARCHAR(45), `DESCRI` VARCHAR(150))
  UPDATE FACTURA  SET
  VENDEDOR = (SELECT ID_USUARIO FROM USUARIO WHERE NOMBRE_USUARIO = VENDEDOR AND ESTADO_TUPLA = TRUE LIMIT 1),
  ID_SUCURSAL = SUCURSAL,
  ID_CLIENTE = CLIENTE,
  FECHA_VENCIMIENTO_FACTURA = VENCE,
  SUBTOTAL_FACTURA = SUBTOTAL,
  DESCUENTO_FACTURA = DESCUENT,
  TOTAL_FACTURA = TOTAL,
  TIPO_FACTURA = TIPO,
  DESCRIPCION_FACTURA = DESCRI
  WHERE ID_FACTURA = CODIGO;
  
  
  CREATE PROCEDURE `ACTUALIZA_FACTURA_PROVEEDOR` (`CODIGO` VARCHAR(25),`VENDEDOR` VARCHAR(25),`VENCE` DATE,`SUCURSAL` INT,  `PROVEEDOR` VARCHAR(15), `SUBTOTAL` FLOAT,
 `DESCUENT` FLOAT, `TOTAL` FLOAT,`TIPO` VARCHAR(45), `DESCRI` VARCHAR(150))
  UPDATE  COTIZACION_PROVEEDOR  SET
  VENDEDOR = (SELECT ID_USUARIO FROM USUARIO WHERE NOMBRE_USUARIO = VENDEDOR AND ESTADO_TUPLA = TRUE LIMIT 1),
  ID_SUCURSAL = SUCURSAL,
  ID_PROVEEDOR = PROVEEDOR,
  FECHA_VENCIMIENTO_FACTURA = VENCE,
  SUBTOTAL_FACTURA = SUBTOTAL,
  DESCUENTO_FACTURA = DESCUENT,
  TOTAL_FACTURA = TOTAL,
  TIPO_FACTURA = TIPO,
  DESCRIPCION_FACTURA = DESCRI
  WHERE ID_FACTURA = CODIGO;
  

  
  CREATE PROCEDURE `NUEVA_COTIZACION_CLIENTE` (`CODIGO` VARCHAR(25),`VENDEDOR` VARCHAR(25),`VENCE` DATE,`SUCURSAL` INT,  `CLIENTE` VARCHAR(15), `SUBTOTAL` FLOAT,
 `DESCUENT` FLOAT, `TOTAL` FLOAT,`TIPO` VARCHAR(45), `DESCRI` VARCHAR(150))
  INSERT INTO FACTURA VALUES (CODIGO,
  (SELECT ID_USUARIO FROM USUARIO WHERE NOMBRE_USUARIO = VENDEDOR AND ESTADO_TUPLA = TRUE LIMIT 1),
  SUCURSAL,CLIENTE,NOW(),VENCE,SUBTOTAL,DESCUENT,TOTAL,TIPO,DESCRI,TRUE,0);
  
    CREATE PROCEDURE `NUEVA_COTIZACION_PROVEEDOR` (`CODIGO` VARCHAR(25),`VENDEDOR` VARCHAR(25),`VENCE` DATE,`SUCURSAL` INT,  `PROVEEDOR` VARCHAR(45), `SUBTOTAL` FLOAT,
 `DESCUENT` FLOAT, `TOTAL` FLOAT,`TIPO` VARCHAR(45), `DESCRI` VARCHAR(150))
  INSERT INTO COTIZACION_PROVEEDOR VALUES (CODIGO,
  (SELECT ID_USUARIO FROM USUARIO WHERE NOMBRE_USUARIO = VENDEDOR AND ESTADO_TUPLA = TRUE LIMIT 1),
  SUCURSAL,PROVEEDOR,NOW(),VENCE,SUBTOTAL,DESCUENT,TOTAL,TIPO,DESCRI,TRUE,0);
  




CREATE PROCEDURE `INGRESA_DETALLE` (`FACTURA` VARCHAR(25), `MERCADERIA` VARCHAR(20),`STOCK` VARCHAR(10),
 `DATOS` VARCHAR(200), `CANTIDAD` INT, `DESCUENTO` FLOAT, `SUBTOTAL` FLOAT, `TOTAL` FLOAT,`NSUCURSAL` VARCHAR(45))
  INSERT INTO DET_FACTURA VALUES (NULL,FACTURA, MERCADERIA,STOCK,(SELECT ID_SUCURSAL FROM SUCURSAL WHERE NOMBRE_SUCURSAL = NSUCURSAL LIMIT 1),DATOS,
  CANTIDAD,DESCUENTO,SUBTOTAL,TOTAL,TRUE);
  
  
CREATE PROCEDURE `INGRESA_DETALLE_PROVEEDOR` (`FACTURA` VARCHAR(25), `MERCADERIA` VARCHAR(20),`STOCK` VARCHAR(10),
 `DATOS` VARCHAR(200), `CANTIDAD` INT, `DESCUENTO` FLOAT, `SUBTOTAL` FLOAT, `TOTAL` FLOAT,`NSUCURSAL` VARCHAR(45))
  INSERT INTO DET_FACTURA VALUES (NULL,FACTURA, MERCADERIA,STOCK,(SELECT ID_SUCURSAL FROM SUCURSAL WHERE NOMBRE_SUCURSAL = NSUCURSAL LIMIT 1),DATOS,
  CANTIDAD,DESCUENTO,SUBTOTAL,TOTAL,TRUE);
 

CREATE PROCEDURE `EDITA_MINIMO_FACTURA` (`CODIGO` VARCHAR(25), `FECHA` DATETIME, `CLIENTE` VARCHAR(15), `USUARIO` VARCHAR(25))
  UPDATE FACTURA SET FECHA_EMISION_FACTURA = FECHA,
   ID_CLIENTE = CLIENTE,
   VENDEDOR = (SELECT ID_USUARIO FROM USUARIO WHERE NOMBRE_USUARIO = USUARIO LIMIT 1) 
   WHERE ID_FACTURA = CODIGO;
   
CREATE PROCEDURE `ACTUALIZA_CUENTA` (`ABONO` FLOAT , `CUENTA` INT )
 UPDATE CUENTA_POR_COBRAR_CLIENTE SET TOTAL_PAGADO = TOTAL_PAGADO + ABONO WHERE ID_CUENTA_POR_COBRAR = CUENTA;
 
 CREATE PROCEDURE `ACTUALIZA_CUENTAP` (`ABONO` FLOAT , `CUENTA` VARCHAR(45))
 UPDATE CUENTA_POR_PAGAR SET TOTAL_PAGADO = TOTAL_PAGADO + ABONO WHERE ID_CUENTA_POR_PAGAR = CUENTA;
 
CREATE PROCEDURE `ACTUALIZA_STOCK` (`CODIGO` INT, `FACTURA` VARCHAR(25), `DESCRIP` VARCHAR(200), `CANTIDAD` FLOAT, 
`DESCUENTO` FLOAT, `SUBTOTAL` FLOAT, `TOTAL` FLOAT)
 UPDATE DET_FACTURA 
 SET DESCRIPCION_DETALLE = DESCRIP,
 CANTIDAD_DET_FACTURA = CANTIDAD,
 DESCUENTO_DET_FACTURA = DESCUENTO,
 SUBTOTAL_DETALLE = SUBTOTAL,
 TOTAL_DET_FACTURA = TOTAL
 WHERE ID_DET_FACTURA = CODIGO;
 
 CREATE PROCEDURE `ACTUALIZA_STOCK_PROVEEDOR` (`CODIGO` INT, `FACTURA` VARCHAR(25), `DESCRIP` VARCHAR(200), `CANTIDAD` FLOAT, 
`DESCUENTO` FLOAT, `SUBTOTAL` FLOAT, `TOTAL` FLOAT)
 UPDATE DETALLE_COTIZACION 
 SET DESCRIPCION_DETALLE = DESCRIP,
 CANTIDAD_DET_FACTURA = CANTIDAD,
 DESCUENTO_DET_FACTURA = DESCUENTO,
 SUBTOTAL_DETALLE = SUBTOTAL,
 TOTAL_DET_FACTURA = TOTAL
 WHERE ID_DET_FACTURA = CODIGO;
 


 
   CREATE PROCEDURE `ACTUALIZA_COTIZACION` (`CODIGO` VARCHAR(25),`VENDEDOR` VARCHAR(25),`VENCE` DATE,`SUCURSAL` INT,  `CLIENTE` VARCHAR(15), `SUBTOTAL` FLOAT,
 `DESCUENT` FLOAT, `TOTAL` FLOAT,`TIPO` VARCHAR(45), `DESCRI` VARCHAR(150))
  UPDATE FACTURA  SET
  VENDEDOR = (SELECT ID_USUARIO FROM USUARIO WHERE NOMBRE_USUARIO = VENDEDOR AND ESTADO_TUPLA = TRUE LIMIT 1),
  ID_SUCURSAL = SUCURSAL,
  ID_CLIENTE = CLIENTE,
  FECHA_VENCIMIENTO_FACTURA = VENCE,
  SUBTOTAL_FACTURA = SUBTOTAL,
  DESCUENTO_FACTURA = DESCUENT,
  TOTAL_FACTURA = TOTAL,
  TIPO_FACTURA = TIPO,
  ESTADO_FACTURA = 1,
  DESCRIPCION_FACTURA = DESCRI
  WHERE ID_FACTURA = CODIGO;
  
    CREATE PROCEDURE `ACTUALIZA_COTIZACION_PROVEEDOR` (`CODIGO` VARCHAR(25),`VENDEDOR` VARCHAR(25),`VENCE` DATE,`SUCURSAL` INT,  `PROVEEDOR` VARCHAR(15), `SUBTOTAL` FLOAT,
 `DESCUENT` FLOAT, `TOTAL` FLOAT,`TIPO` VARCHAR(45), `DESCRI` VARCHAR(150))
  UPDATE COTIZACION_PROVEEDOR  SET
  VENDEDOR = (SELECT ID_USUARIO FROM USUARIO WHERE NOMBRE_USUARIO = VENDEDOR AND ESTADO_TUPLA = TRUE LIMIT 1),
  ID_SUCURSAL = SUCURSAL,
  ID_PROVEEDOR = PROVEEDOR,
  FECHA_VENCIMIENTO_FACTURA = VENCE,
  SUBTOTAL_FACTURA = SUBTOTAL,
  DESCUENTO_FACTURA = DESCUENT,
  TOTAL_FACTURA = TOTAL,
  TIPO_FACTURA = TIPO,
  ESTADO_FACTURA = 1,
  DESCRIPCION_FACTURA = DESCRI
  WHERE ID_FACTURA = CODIGO;
  

  
  CREATE PROCEDURE `NUEVA_SUCURSAL` (`TIPO` VARCHAR(45),`NOMBRE` VARCHAR(45), `DIRECCION` VARCHAR(45), `TELEFONO` VARCHAR(45))
  INSERT INTO SUCURSAL VALUES (NULL, (SELECT ID_TIPO FROM TIPO_SUCURSAL WHERE TIPO_SUCURSAL = TIPO LIMIT 1 ),
  NOMBRE, DIRECCION,TELEFONO, TRUE);
  
  
  CREATE PROCEDURE `UPDATE_SUCURSALES_PRESENTACIONES` (`ID_MERC` VARCHAR(45),`ID_ST` VARCHAR(45), `DESCR` VARCHAR(120),
   `CANTIDAD_PP` DOUBLE, `TOTAL_P` DOUBLE, `CANT_M` DOUBLE, `P_1` DOUBLE, `P_2` DOUBLE,
   `P_3` DOUBLE, `P_4` DOUBLE, `P_5` DOUBLE, `P_6` DOUBLE, `UT_1` DOUBLE, `UT_2` DOUBLE, `UT_3` DOUBLE,
   `UT_4` DOUBLE, `UT_5` DOUBLE, `SUCURSAL` INT)
    UPDATE MERCADERIA_PRESENTACIONES SET
    DESCRIPCION = DESCR,
    CANTIDAD_POR_PRESENTACION = CANTIDAD_PP,
    TOTAL_PRESENTACIONES = TOTAL_P,
    CANTIDAD_MINIMA = CANT_M,
    PRECIO_1 = P_1,
    PRECIO_2 = P_2,
    PRECIO_3 = P_3,
    PRECIO_4 = P_4,
    PRECIO_5 = P_5,
    PRECIO_6 = P_6,
    UTILIDAD_1 = UT_1,
    UTILIDAD_2 = UT_2,
    UTILIDAD_3 = UT_3,
    UTILIDAD_4 = UT_4,
    UTILIDAD_5 = UT_5
    WHERE ID_STOCK = ID_ST  AND ID_SUCURSAL = SUCURSAL;
    
   
 CREATE PROCEDURE `NUEVO_TRASLADO` (`COD_TRASLADO` INT, `USUARIO` VARCHAR(45), `TRASLADO` VARCHAR(45), `DESTINO` VARCHAR(45),`PRODUCTOS` INT)
   INSERT INTO TRASLADOS VALUES (COD_TRASLADO, USUARIO, (SELECT ID_SUCURSAL FROM SUCURSAL WHERE NOMBRE_SUCURSAL = TRASLADO LIMIT 1),
   (SELECT ID_SUCURSAL FROM SUCURSAL WHERE NOMBRE_SUCURSAL = DESTINO LIMIT 1),NOW(), PRODUCTOS, TRUE, TRUE);
       
    
 CREATE PROCEDURE `INGRESA_PRODUCTOS_TRASLADO` (`COD_TRASLADO` INT, `ID_MERCADERIA` VARCHAR(45), `SUCURSAL` VARCHAR(45), `CANTIDAD` FLOAT )
  INSERT INTO PRODUCTOS_TRASLADO VALUES (NULL, COD_TRASLADO, ID_MERCADERIA, (SELECT ID_SUCURSAL FROM SUCURSAL WHERE NOMBRE_SUCURSAL = SUCURSAL LIMIT 1), CANTIDAD);



 
 