
-- ---------------------------------  VISTAS EN C# --------------------------------------------------------

CREATE VIEW -- VISTA CLIENTES DATAGRIDVIEW ----
VISTA_CLIENTES AS
SELECT C.ID_CLIENTE, C.NOMBRE_CLIENTE, C.APELLIDO_CLIENTE,C.DIRECCION_CLIENTE,C.TELEFONO_CLIENTE,
 T.TIPO, C.LIMITE_CREDITO, C.CREDITO_DISPONIBLE, C.DIAS_CREDITO, C.FECHA_INGRESO FROM CLIENTE C
INNER JOIN TIPO_CLIENTE T
ON C.ID_TIPO_CLIENTE = T.ID_TIPO_CLIENTE AND C.ESTADO_TUPLA = TRUE;



CREATE VIEW    -- VISTA PROVEEDORES DATAGRIDVIEW --
VISTA_PROVEEDORES AS
SELECT P.ID_PROVEEDOR,P.NOMBRE_PROVEEDOR,P.EMAIL_PROVEEDOR,P.DIRECCION_PROVEEDOR,P.TELEFONO_PROVEEDOR FROM PROVEEDOR P 
WHERE P.ESTADO_TUPLA = TRUE;



CREATE VIEW    -- VISTA PROVEEDORES DATAGRIDVIEW --
VISTA_SUCURSALES AS
SELECT S.ID_SUCURSAL,(SELECT T.TIPO_SUCURSAL FROM TIPO_SUCURSAL T WHERE ID_TIPO = S.ID_TIPO),S.NOMBRE_SUCURSAL,S.DIRECCION_SUCURSAL,S.TELEFONO_SUCURSAL FROM SUCURSAL S
WHERE S.ESTADO_TUPLA = TRUE;


CREATE VIEW   -- VISTA STOCK DATAGRIDVIEW --
VISTA_MERCADERIA AS 
SELECT M.ID_MERCADERIA,P.NOMBRE_PROVEEDOR, M.DESCRIPCION,M.ACTIVO,M.PRECIO_COMPRA, M.TOTAL_UNIDADES,
M.ID_CLASIFICACION, M.ID_SUCURSAL, S.NOMBRE_SUCURSAL, A.TIPO_MERCADERIA
FROM MERCADERIA M 
INNER JOIN PROVEEDOR P 
ON P.ID_PROVEEDOR = M.ID_PROVEEDOR AND M.ESTADO_TUPLA = TRUE AND ACTIVO = TRUE
INNER JOIN SUCURSAL  S
ON S.ID_SUCURSAL = M.ID_SUCURSAL
INNER JOIN CLASIFICACION_MERCADERIA A 
ON M.ID_CLASIFICACION = A.ID_TIPO;


CREATE VIEW   -- VISTA STOCK DATAGRIDVIEW PARA EDICION DE LA MERCADERIA --
VISTA_MERCADERIA_EDICION AS 
SELECT M.ID_MERCADERIA,P.NOMBRE_PROVEEDOR, M.DESCRIPCION,M.PRECIO_COMPRA, M.TOTAL_UNIDADES,M.ACTIVO,
M.ID_CLASIFICACION, M.ID_SUCURSAL, S.NOMBRE_SUCURSAL, A.TIPO_MERCADERIA
FROM MERCADERIA M 
INNER JOIN PROVEEDOR P 
ON P.ID_PROVEEDOR = M.ID_PROVEEDOR AND M.ESTADO_TUPLA = TRUE
INNER JOIN SUCURSAL  S
ON S.ID_SUCURSAL = M.ID_SUCURSAL
INNER JOIN CLASIFICACION_MERCADERIA A 
ON M.ID_CLASIFICACION = A.ID_TIPO;


CREATE VIEW 
VISTA_STOCK AS 
SELECT S.ID_STOCK, S.DESCRIPCION, S.CANTIDAD_POR_PRESENTACION, S.TOTAL_PRESENTACIONES,S.CANTIDAD_MINIMA,S.PRECIO_1,
S.PRECIO_2, S.PRECIO_3,S.PRECIO_4,S.PRECIO_5, S.PRECIO_6,S.UTILIDAD_1,S.UTILIDAD_2,S.UTILIDAD_3,S.UTILIDAD_4,
S.UTILIDAD_5,S.ID_MERCADERIA,S.ID_SUCURSAL, D.NOMBRE_SUCURSAL, M.DESCRIPCION AS MERCADERIA_DESCRIPCION
 FROM MERCADERIA_PRESENTACIONES S 
 INNER JOIN MERCADERIA M 
 ON M.ID_MERCADERIA = S.ID_MERCADERIA
 INNER JOIN SUCURSAL D
 ON D.ID_SUCURSAL = S.ID_SUCURSAL AND M.ID_SUCURSAL = D.ID_SUCURSAL AND S.ESTADO_TUPLA = TRUE;
 

 
 
CREATE VIEW 
VISTA_CONTROL_COMPRA  AS
 SELECT  C.ID_MERCADERIA, M.DESCRIPCION,C.CANTIDAD_COMPRA, M.PRECIO_COMPRA, C.OTROS_GASTOS, C.SUBTOTAL, C.ID_COMPRA  FROM  CONTROL_COMPRA C
  INNER JOIN MERCADERIA M 
  ON C.ID_MERCADERIA = M.ID_MERCADERIA
  INNER JOIN COMPRA D
  ON D.ID_COMPRA = C.ID_COMPRA AND D.ID_SUCURSAL = M.ID_SUCURSAL;
  


  
CREATE VIEW 
 VISTA_COMPRA AS
  SELECT C.ID_COMPRA,P.NOMBRE_PROVEEDOR, C.FECHA_COMPRA, C.SUBTOTAL_COMPRA, C.DESCUENTO, C.TOTAL_FINAL, S.NOMBRE_SUCURSAL,C.ID_USUARIO  FROM COMPRA C 
  INNER JOIN SUCURSAL S
  ON C.ID_SUCURSAL = S.ID_SUCURSAL AND C.ESTADO_TUPLA = TRUE
  INNER JOIN PROVEEDOR P 
  ON C.ID_PROVEEDOR = P.ID_PROVEEDOR;


 

CREATE VIEW 
 VISTA_MERCADERIA_C AS
  SELECT M.ID_MERCADERIA, S.NOMBRE_SUCURSAL, F.TIPO_MERCADERIA, P.NOMBRE_PROVEEDOR, M.DESCRIPCION, M.PRECIO_COMPRA,
  M.TOTAL_UNIDADES,M.ACTIVO, M.FECHA_INGRESO, S.ID_SUCURSAL, M.ID_CLASIFICACION FROM MERCADERIA M 
  INNER JOIN SUCURSAL S
  ON S.ID_SUCURSAL = M.ID_SUCURSAL 
  INNER JOIN CLASIFICACION_MERCADERIA F 
  ON F.ID_TIPO = M.ID_CLASIFICACION
  INNER JOIN PROVEEDOR P 
  ON P.ID_PROVEEDOR = M.ID_PROVEEDOR
  INNER JOIN CLASIFICACION_MERCADERIA CL
  ON CL.ID_TIPO = M.ID_CLASIFICACION;
  
 

 
 CREATE VIEW 
  TOTAL_PRODUCTOS_SUC1 
  AS SELECT COUNT(*) FROM MERCADERIA WHERE ID_SUCURSAL = 1001 AND ESTADO_TUPLA = TRUE;
  
  CREATE VIEW
	VISTA_CLIENTE_EDIT 
    AS SELECT C.ID_CLIENTE, C.NOMBRE_CLIENTE, C.APELLIDO_CLIENTE, C.DIRECCION_CLIENTE,C.TELEFONO_CLIENTE,
    D.TIPO, C.LIMITE_CREDITO, C.DIAS_CREDITO, C.CREDITO_DISPONIBLE FROM CLIENTE C
    INNER JOIN TIPO_CLIENTE D
    ON D.ID_TIPO_CLIENTE = C.ID_TIPO_CLIENTE;
    

    
 CREATE VIEW 
  VISTA_USUARIOS 
   AS SELECT U.ID_USUARIO, U.ID_ROL, U.NOMBRE_USUARIO, U.EMAIL, U.ESTADO_USUARIO,
   U.LAST_LOGGIN FROM USUARIO U WHERE U.ESTADO_TUPLA = TRUE;
   
 CREATE VIEW 
 BITACORA_VISTA 
  AS SELECT B.ID_OPERACION, B.ID_USUARIO, S.NOMBRE_SUCURSAL, B.OPERACION_BITACORA,
  B.DATO_BITACORA,B.FECHA_HORA,B.HOST_BITACORA FROM BITACORA B 
  INNER JOIN SUCURSAL S 
  ON B.ID_SUCURSAL = S.ID_SUCURSAL;


CREATE VIEW 
 VISTA_GENERAL_PRODUCTO 
  AS SELECT  M.ID_MERCADERIA, M.DESCRIPCION, S.NOMBRE_SUCURSAL,M.TOTAL_UNIDADES, M.PRECIO_COMPRA FROM MERCADERIA M
  INNER JOIN SUCURSAL S
  ON M.ID_SUCURSAL = S.ID_SUCURSAL;
  
  
  CREATE VIEW 
   VISTA_CLIENTE_VENTA 
    AS SELECT  C.ID_CLIENTE, C.NOMBRE_CLIENTE, C.APELLIDO_CLIENTE, C.DIRECCION_CLIENTE, C.LIMITE_CREDITO,
    C.CREDITO_DISPONIBLE, C.DIAS_CREDITO, C.ID_TIPO_CLIENTE FROM CLIENTE C;
    
    
CREATE VIEW 
 VISTA_CODIGOS_ALTERNOS 
  AS SELECT C.ID_STOCK, C.SUBCODIGO, S.ID_SUCURSAL FROM SUBCODIGOS_MERCADERIA C
  INNER JOIN MERCADERIA_PRESENTACIONES M ON
  M.ID_STOCK = C.ID_STOCK AND M.ESTADO_TUPLA = TRUE
  INNER JOIN SUCURSAL S
  ON S.ID_SUCURSAL = M.ID_SUCURSAL;
    


CREATE VIEW 
 VISTA_PRECIOS
  AS SELECT P.PRECIO_1 AS 'PRECIO COSTO', P.PRECIO_2 AS 'PRECIO VENTA 1',P.UTILIDAD_1, P.PRECIO_3  AS 'PRECIO VENTA 2',
  P.UTILIDAD_2, P.PRECIO_4 AS 'PRECIO VENTA 3', P.UTILIDAD_3,  P.PRECIO_5 AS 'PRECIO VENTA 4', P.UTILIDAD_4,
   P.PRECIO_6 AS 'PRECIO VENTA 5', P.UTILIDAD_5, P.ID_STOCK, S.NOMBRE_SUCURSAL
  FROM MERCADERIA_PRESENTACIONES P
  INNER JOIN SUCURSAL S
  ON P.ID_SUCURSAL = S.ID_SUCURSAL;

  
  CREATE VIEW 
   VISTA_FACTURAS
    AS SELECT F.ID_FACTURA, F.FECHA_EMISION_FACTURA, C.NOMBRE_CLIENTE, C.APELLIDO_CLIENTE, F.TIPO_FACTURA,
    F.FECHA_VENCIMIENTO_FACTURA, S.NOMBRE_SUCURSAL, F.TOTAL_FACTURA, U.NOMBRE_USUARIO, S.ID_SUCURSAL,
    F.SUBTOTAL_FACTURA, F.DESCUENTO_FACTURA, F.ESTADO_TUPLA ,F.ID_CLIENTE,C.DIRECCION_CLIENTE FROM FACTURA F
    INNER JOIN CLIENTE C
    ON F.ID_CLIENTE = C.ID_CLIENTE AND F.ESTADO_FACTURA = 1
    INNER JOIN USUARIO U
    ON F.VENDEDOR = U.ID_USUARIO
    INNER JOIN SUCURSAL S
    ON F.ID_SUCURSAL = S.ID_SUCURSAL;
    
    
      CREATE VIEW 
   VISTA_FACTURAS_PRODUCTOS
    AS SELECT F.ID_FACTURA, F.FECHA_EMISION_FACTURA, C.NOMBRE_CLIENTE, C.APELLIDO_CLIENTE, F.TIPO_FACTURA,
    F.FECHA_VENCIMIENTO_FACTURA, S.NOMBRE_SUCURSAL, F.TOTAL_FACTURA, U.NOMBRE_USUARIO, S.ID_SUCURSAL,
    F.SUBTOTAL_FACTURA, F.DESCUENTO_FACTURA, F.ESTADO_TUPLA ,F.ID_CLIENTE,C.DIRECCION_CLIENTE, 
    D.DESCRIPCION_DETALLE FROM FACTURA F
    INNER JOIN CLIENTE C
    ON F.ID_CLIENTE = C.ID_CLIENTE AND F.ESTADO_FACTURA = 1
    INNER JOIN USUARIO U
    ON F.VENDEDOR = U.ID_USUARIO
    INNER JOIN SUCURSAL S
    ON F.ID_SUCURSAL = S.ID_SUCURSAL
    INNER JOIN DET_FACTURA D
    ON F.ID_FACTURA = D.ID_FACTURA AND D.ESTADO_TUPLA = TRUE
    GROUP BY F.ID_FACTURA;
    


    
CREATE VIEW 
 VISTA_KARDEX_COMPRA
  AS SELECT C.FECHA_COMPRA, M.DESCRIPCION, P.NOMBRE_PROVEEDOR, N.NOMBRE_SUCURSAL, S.CANTIDAD_COMPRA, S.PRECIO_COMPRA, M.ID_MERCADERIA FROM COMPRA C
  INNER JOIN CONTROL_COMPRA S
  ON S.ID_COMPRA = C.ID_COMPRA 
  INNER JOIN MERCADERIA M
  ON M.ID_MERCADERIA = S.ID_MERCADERIA AND C.ESTADO_TUPLA = TRUE AND M.ID_SUCURSAL = C.ID_SUCURSAL
  INNER JOIN SUCURSAL N 
  ON M.ID_SUCURSAL = N.ID_SUCURSAL 
  INNER JOIN PROVEEDOR P 
  ON C.ID_PROVEEDOR = P.ID_PROVEEDOR;



CREATE VIEW 
 VISTA_KARDEX_FACTURA
  AS SELECT  F.FECHA_EMISION_FACTURA, D.DESCRIPCION_DETALLE, CONCAT_WS(" ",C.NOMBRE_CLIENTE,C.APELLIDO_CLIENTE),
  S.NOMBRE_SUCURSAL,
  D.CANTIDAD_DET_FACTURA, D.SUBTOTAL_DETALLE, D.ID_MERCADERIA FROM FACTURA F 
   INNER JOIN DET_FACTURA D 
   ON F.ID_FACTURA = D.ID_FACTURA AND F.ESTADO_TUPLA = TRUE
   INNER JOIN SUCURSAL S 
   ON S.ID_SUCURSAL = F.ID_SUCURSAL
   INNER JOIN MERCADERIA M
   ON D.ID_MERCADERIA = M.ID_MERCADERIA AND S.ID_SUCURSAL = M.ID_SUCURSAL
   INNER JOIN CLIENTE C 
   ON F.ID_CLIENTE = C.ID_CLIENTE;


   
   
   
CREATE VIEW 
 VISTA_DETALLE_FACTURA  
  AS SELECT F.ID_FACTURA, D.ID_MERCADERIA, D.DESCRIPCION_DETALLE, D.CANTIDAD_DET_FACTURA, D.SUBTOTAL_DETALLE,
  D.DESCUENTO_DET_FACTURA, D.TOTAL_DET_FACTURA, S.NOMBRE_SUCURSAL,
  D.ID_STOCK, P.CANTIDAD_POR_PRESENTACION,D.ID_DET_FACTURA, P.PRECIO_1  FROM DET_FACTURA D 
  INNER JOIN FACTURA F 
  ON F.ID_FACTURA = D.ID_FACTURA AND D.ESTADO_TUPLA = TRUE
  INNER JOIN SUCURSAL S 
  ON F.ID_SUCURSAL = S.ID_SUCURSAL
  INNER JOIN MERCADERIA_PRESENTACIONES P 
  ON P.ID_STOCK = D.ID_STOCK AND P.ID_SUCURSAL = D.ID_SUCURSAL;


CREATE VIEW 
 VISTA_DETALLE_PROVEEDOR  
  AS SELECT F.ID_FACTURA, D.ID_MERCADERIA, D.DESCRIPCION_DETALLE, D.CANTIDAD_DET_FACTURA, D.SUBTOTAL_DETALLE,
  D.DESCUENTO_DET_FACTURA, D.TOTAL_DET_FACTURA, S.NOMBRE_SUCURSAL,
  D.ID_STOCK, P.CANTIDAD_POR_PRESENTACION,D.ID_DET_FACTURA, P.PRECIO_1  FROM DETALLE_COTIZACION D 
  INNER JOIN COTIZACION_PROVEEDOR F 
  ON F.ID_FACTURA = D.ID_FACTURA AND D.ESTADO_TUPLA = TRUE
  INNER JOIN SUCURSAL S 
  ON F.ID_SUCURSAL = S.ID_SUCURSAL
  INNER JOIN MERCADERIA_PRESENTACIONES P 
  ON P.ID_STOCK = D.ID_STOCK AND P.ID_SUCURSAL = D.ID_SUCURSAL;
  
 

  
 



  CREATE VIEW 
VISTA_STOCK_VENTA AS 
SELECT S.ID_STOCK,S.ID_MERCADERIA,M.DESCRIPCION AS MERCADERIA_DESCRIPCIONS, S.DESCRIPCION, S.PRECIO_2, 
 D.NOMBRE_SUCURSAL ,S.CANTIDAD_POR_PRESENTACION, S.PRECIO_1
 FROM MERCADERIA_PRESENTACIONES S 
 INNER JOIN MERCADERIA M 
 ON M.ID_MERCADERIA = S.ID_MERCADERIA AND M.ACTIVO = TRUE
 INNER JOIN SUCURSAL D
 ON D.ID_SUCURSAL = S.ID_SUCURSAL AND S.ESTADO_TUPLA = TRUE;
 
  
  
  
  CREATE VIEW 
   VISTA_FACTURAS_CLIENTE
    AS SELECT F.ID_FACTURA, F.FECHA_EMISION_FACTURA, F.TIPO_FACTURA,
    F.FECHA_VENCIMIENTO_FACTURA, F.TOTAL_FACTURA,F.ID_CLIENTE FROM FACTURA F
    INNER JOIN CLIENTE C
    ON F.ID_CLIENTE = C.ID_CLIENTE
    INNER JOIN USUARIO U
    ON F.VENDEDOR = U.ID_USUARIO
    INNER JOIN SUCURSAL S
    ON F.ID_SUCURSAL = S.ID_SUCURSAL;

 --     VISTAS PRA CUENTAS POR  COBRRAR --
  
 CREATE VIEW 
  VISTA_CUENTAS_COBRAR 
   AS SELECT F.ID_FACTURA, S.ID_CLIENTE, S.NOMBRE_CLIENTE,S.APELLIDO_CLIENTE,
   F.FECHA_EMISION_FACTURA,F.FECHA_VENCIMIENTO_FACTURA, C.ESTADO_TUPLA, C.ID_CUENTA_POR_COBRAR
   FROM CUENTA_POR_COBRAR_CLIENTE C
   INNER JOIN CLIENTE S 
   ON C.ID_CLIENTE = S.ID_CLIENTE
   INNER JOIN FACTURA F 
   ON C.ID_FACTURA = F.ID_FACTURA AND F.ID_CLIENTE = S.ID_CLIENTE;
 

 CREATE VIEW 
  VISTA_POR_CLIENTE_COBRAR 
   AS SELECT P.ID_CUENTA_POR_COBRAR, P.ID_CLIENTE , C.NOMBRE_CLIENTE, C.APELLIDO_CLIENTE, COUNT(*), 
   (SELECT SUM(TOTAL_PAGADO) FROM CUENTA_POR_COBRAR_CLIENTE WHERE ID_CLIENTE = P.ID_CLIENTE AND ESTADO_TUPLA = TRUE) AS PAGADO,
   P.FECHA_PAGO, P.ESTADO_TUPLA, C.DIRECCION_CLIENTE
   FROM CUENTA_POR_COBRAR_CLIENTE P
   INNER JOIN FACTURA F
   ON P.ID_FACTURA = F.ID_FACTURA
   INNER JOIN CLIENTE C
   ON P.ID_CLIENTE = C.ID_CLIENTE WHERE P.ESTADO_TUPLA = TRUE AND P.ESTADO_CUENTA = TRUE GROUP BY P.ID_CLIENTE;


CREATE VIEW 
  VISTA_POR_CLIENTE_COBRARF 
   AS SELECT P.ID_CUENTA_POR_COBRAR, P.ID_CLIENTE , C.NOMBRE_CLIENTE, C.APELLIDO_CLIENTE, COUNT(*), 
   (SELECT SUM(TOTAL_PAGADO) FROM CUENTA_POR_COBRAR_CLIENTE WHERE ID_CLIENTE = P.ID_CLIENTE AND ESTADO_TUPLA = TRUE) AS PAGADO,
   P.FECHA_PAGO, P.ESTADO_TUPLA, C.DIRECCION_CLIENTE
   FROM CUENTA_POR_COBRAR_CLIENTE P
   INNER JOIN FACTURA F
   ON P.ID_FACTURA = F.ID_FACTURA
   INNER JOIN CLIENTE C
   ON P.ID_CLIENTE = C.ID_CLIENTE WHERE P.ESTADO_TUPLA = FALSE AND P.ESTADO_CUENTA = TRUE GROUP BY P.ID_CLIENTE;

  CREATE VIEW 
   VISTA_CUENTA_CLIENTE 
     AS SELECT S.LIMITE_CREDITO, S.CREDITO_DISPONIBLE, C.ID_FACTURA, F.FECHA_EMISION_FACTURA, F.TIPO_FACTURA, 
     F.FECHA_VENCIMIENTO_FACTURA, F.TOTAL_FACTURA, C.TOTAL_PAGADO, C.ID_CUENTA_POR_COBRAR, 
     F.ID_CLIENTE FROM CUENTA_POR_COBRAR_CLIENTE C
     INNER JOIN FACTURA F 
     ON C.ID_FACTURA = F.ID_FACTURA AND C.ESTADO_TUPLA = TRUE AND C.ESTADO_CUENTA = TRUE
     INNER JOIN CLIENTE S 
     ON C.ID_CLIENTE = S.ID_CLIENTE;
     
     CREATE VIEW 
   VISTA_CUENTA_CLIENTEF
     AS SELECT S.LIMITE_CREDITO, S.CREDITO_DISPONIBLE, C.ID_FACTURA, F.FECHA_EMISION_FACTURA, F.TIPO_FACTURA, 
     F.FECHA_VENCIMIENTO_FACTURA, F.TOTAL_FACTURA, C.TOTAL_PAGADO, C.ID_CUENTA_POR_COBRAR, 
     F.ID_CLIENTE FROM CUENTA_POR_COBRAR_CLIENTE C
     INNER JOIN FACTURA F 
     ON C.ID_FACTURA = F.ID_FACTURA AND C.ESTADO_TUPLA = FALSE AND C.ESTADO_CUENTA = TRUE
     INNER JOIN CLIENTE S 
     ON C.ID_CLIENTE = S.ID_CLIENTE;
  


  CREATE VIEW 
   VISTA_ABONOS 
    AS SELECT P.ID_PAGO, P.ID_CUENTA_POR_COBRAR, P.FECHA_PAGO, P.SUBTOTAL,
    P.DESCUENTO, P.TOTAL FROM PAGO_CLIENTE P WHERE P.ESTADO_TUPLA = TRUE ;
  

 --     VISTAS PRA CUENTAS POR PAGAR --
 

 
 
 
  CREATE VIEW 
  VISTA_PAGAR 
   AS SELECT P.ID_CUENTA_POR_PAGAR, P.ID_PROVEEDOR , C.NOMBRE_PROVEEDOR, COUNT(*), 
   (SELECT SUM(TOTAL_PAGADO) FROM CUENTA_POR_PAGAR WHERE ID_PROVEEDOR = P.ID_PROVEEDOR 
	AND ESTADO_TUPLA = TRUE) AS PAGADO,
   P.FECHA_PAGO, P.ESTADO_TUPLA, C.DIRECCION_PROVEEDOR
   FROM CUENTA_POR_PAGAR P
   INNER JOIN COMPRA D 
   ON D.ID_COMPRA = P.ID_COMPRA
   INNER JOIN PROVEEDOR C
   ON P.ID_PROVEEDOR = C.ID_PROVEEDOR WHERE P.ESTADO_TUPLA = TRUE AND P.ESTADO_CUENTA = TRUE GROUP BY
   P.ID_PROVEEDOR;
   

   

   
   CREATE VIEW 
   VISTA_CUENTA_PAGAR 
     AS SELECT   C.ID_COMPRA, F.FECHA_COMPRA, C.DESCRIPCION, 
     C.FECHA_PAGO, C.TOTAL_COMPRA, C.TOTAL_PAGADO, C.ID_CUENTA_POR_PAGAR, 
     S.ID_PROVEEDOR FROM CUENTA_POR_PAGAR C
     INNER JOIN COMPRA F 
     ON C.ID_COMPRA = F.ID_COMPRA AND C.ESTADO_TUPLA = TRUE AND C.ESTADO_CUENTA = TRUE
     INNER JOIN PROVEEDOR S 
     ON C.ID_PROVEEDOR = S.ID_PROVEEDOR;


  CREATE VIEW 
   VISTA_ABONOSP
    AS SELECT P.ID_PAGO, P.ID_CUENTA_POR_PAGAR, P.FECHA_PAGO, P.SUBTTOTAL_PAGO,
    P.DESCUENTO, P.TOTAL_PAGO FROM PAGO_CUENTA P WHERE P.ESTADO_TUPLA = TRUE ;


 CREATE VIEW 
  VISTA_PAGARF 
   AS SELECT P.ID_CUENTA_POR_PAGAR, P.ID_PROVEEDOR , C.NOMBRE_PROVEEDOR, COUNT(*), 
   (SELECT SUM(TOTAL_PAGADO) FROM CUENTA_POR_PAGAR WHERE ID_PROVEEDOR = P.ID_PROVEEDOR 
	AND ESTADO_TUPLA = TRUE) AS PAGADO,
   P.FECHA_PAGO, P.ESTADO_TUPLA, C.DIRECCION_PROVEEDOR
   FROM CUENTA_POR_PAGAR P
   INNER JOIN COMPRA D 
   ON D.ID_COMPRA = P.ID_COMPRA
   INNER JOIN PROVEEDOR C
   ON P.ID_PROVEEDOR = C.ID_PROVEEDOR WHERE P.ESTADO_TUPLA = FALSE AND P.ESTADO_CUENTA = TRUE GROUP BY
   P.ID_PROVEEDOR;
   

   
   
     CREATE VIEW 
   VISTA_CUENTA_PAGARF 
     AS SELECT   C.ID_COMPRA, F.FECHA_COMPRA, C.DESCRIPCION, 
     C.FECHA_PAGO, C.TOTAL_COMPRA, C.TOTAL_PAGADO, C.ID_CUENTA_POR_PAGAR, 
     S.ID_PROVEEDOR FROM CUENTA_POR_PAGAR C
     INNER JOIN COMPRA F 
     ON C.ID_COMPRA = F.ID_COMPRA AND C.ESTADO_TUPLA = FALSE AND C.ESTADO_CUENTA = TRUE
     INNER JOIN PROVEEDOR S 
     ON C.ID_PROVEEDOR = S.ID_PROVEEDOR;
     
     -- APERTUA Y CIERRES DE CAJA --
     
	CREATE VIEW 
     VISTA_CAJAS 
      AS SELECT C.ID_CAJA, U.NOMBRE_USUARIO, S.NOMBRE_SUCURSAL, C.APERTURA_CAJA,
      C.MONTO_APERTURA_CAJA, C.TOTAL_FACTURADO_CAJA,  C.ESTADO_TUPLA, C.ID_USUARIO,
      C.ID_SUCURSAL, C.OBSERVACIONES_CAJA FROM CAJA C
      INNER JOIN USUARIO U
      ON C.ID_USUARIO = U.ID_USUARIO AND U.ESTADO_TUPLA = TRUE AND C.ESTADO_CAJA = TRUE
      INNER JOIN SUCURSAL S
      ON C.ID_SUCURSAL = S.ID_SUCURSAL AND C.ESTADO_TUPLA = TRUE;
     
     
     
  CREATE VIEW 
   CAJA_FACTURAS
    AS SELECT F.ID_FACTURA, C.NOMBRE_CLIENTE, C.APELLIDO_CLIENTE, F.TIPO_FACTURA, D.DESCRIPCION ,F.SUBTOTAL_FACTURA, F.DESCUENTO_FACTURA,
    F.TOTAL_FACTURA ,D.ID_DET_CAJA, D.ID_CAJA FROM DET_CAJA D
    INNER JOIN FACTURA F 
    ON D.ID_FACTURA = F.ID_FACTURA AND D.ESTADO_TUPLA = TRUE
    INNER JOIN CLIENTE C 
    ON F.ID_CLIENTE = C.ID_CLIENTE;
    
    
    
    
   -- UPDATE CAJA SET ESTADO_TUPLA = FALSE  WHERE APERTURA_CAJA < CURDATE();
    
    
   -- select sum(total_factura) from caja_facturas where tipo_factura = 'EFECTIVO' where id_caja = ;

    CREATE VIEW 
     VISTA_CAJASF 
      AS SELECT C.ID_CAJA, U.NOMBRE_USUARIO, S.NOMBRE_SUCURSAL, C.APERTURA_CAJA,
      C.MONTO_APERTURA_CAJA, C.TOTAL_FACTURADO_CAJA,  C.ESTADO_TUPLA, C.ID_USUARIO,
      C.ID_SUCURSAL, C.OBSERVACIONES_CAJA FROM CAJA C
      INNER JOIN USUARIO U
      ON C.ID_USUARIO = U.ID_USUARIO AND U.ESTADO_TUPLA = TRUE AND C.ESTADO_CAJA = TRUE
      INNER JOIN SUCURSAL S
      ON C.ID_SUCURSAL = S.ID_SUCURSAL AND C.ESTADO_TUPLA = FALSE;
      
      
      
	CREATE VIEW 
     VISTA_DEVOLUCIONES 
      AS SELECT D.ID_DEVOLUCION, D.ID_FACTURA, C.NOMBRE_CLIENTE, C.APELLIDO_CLIENTE,D.TIPO_DEVOLUCION ,
      D.FECHA_DEVOLUCION, F.SUBTOTAL_FACTURA, F.DESCUENTO_FACTURA, F.TOTAL_FACTURA, F.TIPO_FACTURA, (SELECT NOMBRE_USUARIO FROM USUARIO WHERE ID_USUARIO = F.VENDEDOR) AS VENDEDOR, F.ID_CLIENTE FROM DEVOLUCION D
      INNER JOIN FACTURA F 
      ON D.ID_FACTURA = F.ID_FACTURA AND F.ESTADO_TUPLA = FALSE AND D.ESTADO_TUPLA = TRUE
      INNER JOIN CLIENTE C
      ON F.ID_CLIENTE = C.ID_CLIENTE;
      
      
      
      
      
      -- DROP VIEW VISTA_DEVOLUCIONES;
    


   
-- SELECT * FROM VISTA_KARDEX_FACTURA WHERE FECHA_EMISION_FACTURA >= date_sub(curdate(), interval 1 month) ;



 --       APARTADO DE DEVOLUCIONES -- 
 
 
   CREATE VIEW 
   VISTA_COTIZACION
    AS SELECT F.ID_FACTURA, F.FECHA_EMISION_FACTURA, C.NOMBRE_CLIENTE, C.APELLIDO_CLIENTE, F.TIPO_FACTURA,
    F.FECHA_VENCIMIENTO_FACTURA, S.NOMBRE_SUCURSAL, F.TOTAL_FACTURA, U.NOMBRE_USUARIO, S.ID_SUCURSAL,
    F.SUBTOTAL_FACTURA, F.DESCUENTO_FACTURA, F.ESTADO_TUPLA ,F.ID_CLIENTE, C.DIRECCION_CLIENTE FROM FACTURA F
    INNER JOIN CLIENTE C
    ON F.ID_CLIENTE = C.ID_CLIENTE AND F.ESTADO_FACTURA = 0 AND F.ESTADO_TUPLA = TRUE
    INNER JOIN USUARIO U
    ON F.VENDEDOR = U.ID_USUARIO
    INNER JOIN SUCURSAL S
    ON F.ID_SUCURSAL = S.ID_SUCURSAL;
    
    
    


    
       CREATE VIEW 
   VISTA_COTIZACION_PROVEEDOR
    AS SELECT F.ID_FACTURA, F.FECHA_EMISION_FACTURA, C.NOMBRE_PROVEEDOR, C.EMAiL_PROVEEDOR, F.TIPO_FACTURA,
    F.FECHA_VENCIMIENTO_FACTURA, S.NOMBRE_SUCURSAL, F.TOTAL_FACTURA, U.NOMBRE_USUARIO, S.ID_SUCURSAL,
    F.SUBTOTAL_FACTURA, F.DESCUENTO_FACTURA, F.ESTADO_TUPLA ,F.ID_PROVEEDOR, C.DIRECCION_PROVEEDOR FROM COTIZACION_PROVEEDOR F
    INNER JOIN PROVEEDOR C
    ON F.ID_PROVEEDOR = C.ID_PROVEEDOR AND F.ESTADO_FACTURA = 0 
    INNER JOIN USUARIO U
    ON F.VENDEDOR = U.ID_USUARIO
    INNER JOIN SUCURSAL S
    ON F.ID_SUCURSAL = S.ID_SUCURSAL;
    
    
    CREATE VIEW VISTA_SUCURSALES_PRECIOS AS
    SELECT S.ID_SUCURSAL, S.NOMBRE_SUCURSAL, M.ID_MERCADERIA FROM SUCURSAL S
    INNER JOIN MERCADERIA M ON M.ID_SUCURSAL = S.ID_SUCURSAL
    ORDER BY ID_MERCADERIA;
    
    
    

CREATE VIEW   -- VISTA STOCK DATAGRIDVIEW PARA EDICION DE LA MERCADERIA --
VISTA_MERCADERIA_EDICION AS 
SELECT M.ID_MERCADERIA,P.NOMBRE_PROVEEDOR, M.DESCRIPCION,M.PRECIO_COMPRA, M.TOTAL_UNIDADES,M.ACTIVO,
M.ID_CLASIFICACION, M.ID_SUCURSAL, S.NOMBRE_SUCURSAL, A.TIPO_MERCADERIA
FROM MERCADERIA M 
INNER JOIN PROVEEDOR P 
ON P.ID_PROVEEDOR = M.ID_PROVEEDOR AND M.ESTADO_TUPLA = TRUE
INNER JOIN SUCURSAL  S
ON S.ID_SUCURSAL = M.ID_SUCURSAL
INNER JOIN CLASIFICACION_MERCADERIA A 
ON M.ID_CLASIFICACION = A.ID_TIPO;
    
    
 CREATE VIEW VISTA_TRASLADOS
  AS SELECT T.ID_TRASLADO, T.FECHA_TRASLADO, S.NOMBRE_USUARIO, 
  (SELECT NOMBRE_SUCURSAL FROM SUCURSAL WHERE ID_SUCURSAL = T.TRASLADO_DE_SUCURSAL) AS TRASLADO_DE ,
  (SELECT NOMBRE_SUCURSAL FROM SUCURSAL WHERE ID_SUCURSAL = T.TRASLADO_A_SUCURSAL) AS TRASLADO_DESTINO,
  T.NUMERO_PRODUCTOS, T.ESTADO_TRASLADO
  FROM TRASLADOS T 
  INNER JOIN USUARIO S 
  ON T.ID_USUARIO = S.ID_USUARIO AND T.ESTADO_TUPLA = TRUE;
  
  CREATE VIEW VISTA_DETALLE_TRASLADO 
   AS SELECT P.ID_PRODUCTOS_TRASLADO, M.ID_MERCADERIA, M.DESCRIPCION,
   (SELECT NOMBRE_PROVEEDOR FROM PROVEEDOR WHERE ID_PROVEEDOR = M.ID_PROVEEDOR) AS PROVEEDOR, 
   (SELECT NOMBRE_SUCURSAL FROM SUCURSAL WHERE ID_SUCURSAL = P.ID_SUCURSAL) AS SUCURSAL_ORIGEN,
   P.UNIDADES_TRASLADADAS, P.ID_TRASLADO FROM PRODUCTOS_TRASLADO P 
   INNER JOIN MERCADERIA M 
   ON P.ID_MERCADERIA = M.ID_MERCADERIA AND M.ID_SUCURSAL = P.ID_SUCURSAL
   INNER JOIN TRASLADOS T 
   ON P.ID_TRASLADO = T.ID_TRASLADO;
   
CREATE VIEW VISTA_TRASLADOS_REPORTES AS 
SELECT P.ID_PRODUCTOS_TRASLADO, M.ID_MERCADERIA, M.DESCRIPCION,
   (SELECT NOMBRE_PROVEEDOR FROM PROVEEDOR WHERE ID_PROVEEDOR = M.ID_PROVEEDOR) AS PROVEEDOR, 
   (SELECT NOMBRE_SUCURSAL FROM SUCURSAL WHERE ID_SUCURSAL = P.ID_SUCURSAL) AS SUCURSAL_ORIGEN,
   P.UNIDADES_TRASLADADAS, P.ID_TRASLADO, T.TRASLADO_A_SUCURSAL, 
   (SELECT NOMBRE_SUCURSAL FROM SUCURSAL WHERE ID_SUCURSAL = T.TRASLADO_A_SUCURSAL) AS DESTINO,
   (SELECT NOMBRE_SUCURSAL FROM SUCURSAL WHERE ID_SUCURSAL = T.TRASLADO_DE_SUCURSAL) AS ORIGEN,
   T.FECHA_TRASLADO
   FROM PRODUCTOS_TRASLADO P 
   INNER JOIN MERCADERIA M 
   ON P.ID_MERCADERIA = M.ID_MERCADERIA AND M.ID_SUCURSAL = P.ID_SUCURSAL
   INNER JOIN TRASLADOS T 
   ON P.ID_TRASLADO = T.ID_TRASLADO
   ORDER BY T.FECHA_TRASLADO DESC LIMIT 65;
   


    


      


  
 

    
	