 
 CREATE PROCEDURE `UPDATE_PRIVILEGIOS` (IN`ID_USER` VARCHAR(25), IN `ID_ROL` VARCHAR(45), IN `ROL` VARCHAR(45), 
   IN `A_CAJA` BOOL,`C_CAJA` BOOL, `A_FACTURA` BOOL,`DEVOLUCION` BOOL, `REPORTES` BOOL, `E_CLIENTE` BOOL,
      `I_CLIENTE` BOOL,`I_PROVEEDORES` BOOL, `E_PROVEEDORES` BOOL,`BITAC` BOOL,`C_COBRAR` BOOL, `C_PAGAR` BOOL, 
      `I_USERS` BOOL,`E_USERS` BOOL, `C_MERCA` BOOL, `COMP` BOOL, `T_MERCA` BOOL,`KARD` BOOL)
      UPDATE  PRIVILEGIOS_USUARIO SET
      APERTURA_CAJA = A_CAJA,
      CIERRE_CAJA = C_CAJA,
      ANULAR_FACTURA = A_FACTURA,
      DEVOLUCIONES = DEVOLUCION,
      VER_REPORTES = REPORTES,
      ELIMINAR_CLIENTE = E_CLIENTE,
      INGRESAR_CLIENTE = I_CLIENTE,
      INGRESO_PROVEEDOR = I_PROVEEDORES,
      ELIMINAR_PROVEEDOR = E_PROVEEDORES,
      BITACORA = BITAC,
      CUENTAS_COBRAR = C_COBRAR,
      CUENTAS_PAGAR = C_PAGAR,
      INGRESO_USUARIOS = I_USERS,
      ELIMINAR_USUARIOS = E_USERS,
      CONSULTAR_MERCADERIA = C_MERCA,
      COMPRAS = COMP,
      KARDEX = KARD,
      TRASLADO_MERCADERIA = T_MERCA WHERE USUARIO_ID_USUARIO = ID_USER AND ROL_ID_ROL = ROL;

 